package com.ar.dev.tierra.api.model;
// Generated 17/02/2016 00:47:04 by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DetalleFactura generated by hbm2java
 */
@Entity
@Table(name = "detalle_factura")
public class DetalleFactura implements Serializable {

    private int idDetalleFactura;
    private Factura factura;
    private Producto producto;
    private int cantidadDetalle;
    private int totalDetalle;
    private Integer descuentoDetalle;
    private boolean estadoDetalle;
    private int usuarioCreacion;
    private Integer usuarioModificacion;
    private Date fechaCreacion;
    private Date fechaModificacion;

    public DetalleFactura() {
    }

    public DetalleFactura(int idDetalleFactura, Factura factura, Producto producto, int cantidadDetalle, int totalDetalle, boolean estadoDetalle, int usuarioCreacion, Date fechaCreacion) {
        this.idDetalleFactura = idDetalleFactura;
        this.factura = factura;
        this.producto = producto;
        this.cantidadDetalle = cantidadDetalle;
        this.totalDetalle = totalDetalle;
        this.estadoDetalle = estadoDetalle;
        this.usuarioCreacion = usuarioCreacion;
        this.fechaCreacion = fechaCreacion;
    }

    public DetalleFactura(int idDetalleFactura, Factura factura, Producto producto, int cantidadDetalle, int totalDetalle, Integer descuentoDetalle, boolean estadoDetalle, int usuarioCreacion, Integer usuarioModificacion, Date fechaCreacion, Date fechaModificacion) {
        this.idDetalleFactura = idDetalleFactura;
        this.factura = factura;
        this.producto = producto;
        this.cantidadDetalle = cantidadDetalle;
        this.totalDetalle = totalDetalle;
        this.descuentoDetalle = descuentoDetalle;
        this.estadoDetalle = estadoDetalle;
        this.usuarioCreacion = usuarioCreacion;
        this.usuarioModificacion = usuarioModificacion;
        this.fechaCreacion = fechaCreacion;
        this.fechaModificacion = fechaModificacion;
    }

    @Id

    @Column(name = "id_detalle_factura", unique = true, nullable = false)
    public int getIdDetalleFactura() {
        return this.idDetalleFactura;
    }

    public void setIdDetalleFactura(int idDetalleFactura) {
        this.idDetalleFactura = idDetalleFactura;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "id_factura", nullable = false)
    public Factura getFactura() {
        return this.factura;
    }

    public void setFactura(Factura factura) {
        this.factura = factura;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "id_producto", nullable = false)
    public Producto getProducto() {
        return this.producto;
    }

    public void setProducto(Producto producto) {
        this.producto = producto;
    }

    @Column(name = "cantidad_detalle", nullable = false)
    public int getCantidadDetalle() {
        return this.cantidadDetalle;
    }

    public void setCantidadDetalle(int cantidadDetalle) {
        this.cantidadDetalle = cantidadDetalle;
    }

    @Column(name = "total_detalle", nullable = false)
    public int getTotalDetalle() {
        return this.totalDetalle;
    }

    public void setTotalDetalle(int totalDetalle) {
        this.totalDetalle = totalDetalle;
    }

    @Column(name = "descuento_detalle")
    public Integer getDescuentoDetalle() {
        return this.descuentoDetalle;
    }

    public void setDescuentoDetalle(Integer descuentoDetalle) {
        this.descuentoDetalle = descuentoDetalle;
    }

    @Column(name = "estado_detalle", nullable = false)
    public boolean isEstadoDetalle() {
        return this.estadoDetalle;
    }

    public void setEstadoDetalle(boolean estadoDetalle) {
        this.estadoDetalle = estadoDetalle;
    }

    @Column(name = "usuario_creacion", nullable = false)
    public int getUsuarioCreacion() {
        return this.usuarioCreacion;
    }

    public void setUsuarioCreacion(int usuarioCreacion) {
        this.usuarioCreacion = usuarioCreacion;
    }

    @Column(name = "usuario_modificacion")
    public Integer getUsuarioModificacion() {
        return this.usuarioModificacion;
    }

    public void setUsuarioModificacion(Integer usuarioModificacion) {
        this.usuarioModificacion = usuarioModificacion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fecha_creacion", nullable = false, length = 35)
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }

    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fecha_modificacion", length = 35)
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }

    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }

}
