package com.ar.dev.tierra.api.model;
// Generated 17/02/2016 00:47:04 by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EntidadBancaria generated by hbm2java
 */
@Entity
@Table(name = "entidad_bancaria")
public class EntidadBancaria implements Serializable {

    private int idEntidadMonetaria;
    private String nombreEntidad;
    private String direccionEntidad;
    private String telefonoEntidad;
    private boolean estadoEntidad;
    private Date fechaCreaciion;
    private Date fechaModificacion;
    private int usuarioCreacion;
    private Integer usuarioModificacion;

    public EntidadBancaria() {
    }

    public EntidadBancaria(int idEntidadMonetaria, String nombreEntidad, boolean estadoEntidad, Date fechaCreaciion, int usuarioCreacion) {
        this.idEntidadMonetaria = idEntidadMonetaria;
        this.nombreEntidad = nombreEntidad;
        this.estadoEntidad = estadoEntidad;
        this.fechaCreaciion = fechaCreaciion;
        this.usuarioCreacion = usuarioCreacion;
    }

    public EntidadBancaria(int idEntidadMonetaria, String nombreEntidad, String direccionEntidad, String telefonoEntidad, boolean estadoEntidad, Date fechaCreaciion, Date fechaModificacion, int usuarioCreacion, Integer usuarioModificacion) {
        this.idEntidadMonetaria = idEntidadMonetaria;
        this.nombreEntidad = nombreEntidad;
        this.direccionEntidad = direccionEntidad;
        this.telefonoEntidad = telefonoEntidad;
        this.estadoEntidad = estadoEntidad;
        this.fechaCreaciion = fechaCreaciion;
        this.fechaModificacion = fechaModificacion;
        this.usuarioCreacion = usuarioCreacion;
        this.usuarioModificacion = usuarioModificacion;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE)
    @Column(name = "id_entidad_monetaria", unique = true, nullable = false)
    public int getIdEntidadMonetaria() {
        return this.idEntidadMonetaria;
    }

    public void setIdEntidadMonetaria(int idEntidadMonetaria) {
        this.idEntidadMonetaria = idEntidadMonetaria;
    }

    @Column(name = "nombre_entidad", nullable = false, length = 150)
    public String getNombreEntidad() {
        return this.nombreEntidad;
    }

    public void setNombreEntidad(String nombreEntidad) {
        this.nombreEntidad = nombreEntidad;
    }

    @Column(name = "direccion_entidad", length = 150)
    public String getDireccionEntidad() {
        return this.direccionEntidad;
    }

    public void setDireccionEntidad(String direccionEntidad) {
        this.direccionEntidad = direccionEntidad;
    }

    @Column(name = "telefono_entidad", length = 100)
    public String getTelefonoEntidad() {
        return this.telefonoEntidad;
    }

    public void setTelefonoEntidad(String telefonoEntidad) {
        this.telefonoEntidad = telefonoEntidad;
    }

    @Column(name = "estado_entidad", nullable = false)
    public boolean isEstadoEntidad() {
        return this.estadoEntidad;
    }

    public void setEstadoEntidad(boolean estadoEntidad) {
        this.estadoEntidad = estadoEntidad;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha_creaciion", nullable = false, length = 13)
    public Date getFechaCreaciion() {
        return this.fechaCreaciion;
    }

    public void setFechaCreaciion(Date fechaCreaciion) {
        this.fechaCreaciion = fechaCreaciion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha_modificacion", length = 13)
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }

    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }

    @Column(name = "usuario_creacion", nullable = false)
    public int getUsuarioCreacion() {
        return this.usuarioCreacion;
    }

    public void setUsuarioCreacion(int usuarioCreacion) {
        this.usuarioCreacion = usuarioCreacion;
    }

    @Column(name = "usuario_modificacion")
    public Integer getUsuarioModificacion() {
        return this.usuarioModificacion;
    }

    public void setUsuarioModificacion(Integer usuarioModificacion) {
        this.usuarioModificacion = usuarioModificacion;
    }
}
