package com.ar.dev.tierra.api.model;
// Generated 17/02/2016 00:47:04 by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MetodoPagoFactura generated by hbm2java
 */
@Entity
@Table(name = "metodo_pago_factura")
public class MetodoPagoFactura implements Serializable {

    private int idMetodoPagoFactura;
    private Factura factura;
    private PlanPago planPago;
    private int montoPago;
    private boolean estado;
    private Date fechaCreacion;
    private Date fechaModificacion;
    private int usuarioCreacion;
    private Integer usuarioModificacion;

    public MetodoPagoFactura() {
    }

    public MetodoPagoFactura(int idMetodoPagoFactura, Factura factura, PlanPago planPago, int montoPago, boolean estado, Date fechaCreacion, int usuarioCreacion) {
        this.idMetodoPagoFactura = idMetodoPagoFactura;
        this.factura = factura;
        this.planPago = planPago;
        this.montoPago = montoPago;
        this.estado = estado;
        this.fechaCreacion = fechaCreacion;
        this.usuarioCreacion = usuarioCreacion;
    }

    public MetodoPagoFactura(int idMetodoPagoFactura, Factura factura, PlanPago planPago, int montoPago, boolean estado, Date fechaCreacion, Date fechaModificacion, int usuarioCreacion, Integer usuarioModificacion) {
        this.idMetodoPagoFactura = idMetodoPagoFactura;
        this.factura = factura;
        this.planPago = planPago;
        this.montoPago = montoPago;
        this.estado = estado;
        this.fechaCreacion = fechaCreacion;
        this.fechaModificacion = fechaModificacion;
        this.usuarioCreacion = usuarioCreacion;
        this.usuarioModificacion = usuarioModificacion;
    }

    @Id

    @Column(name = "id_metodo_pago_factura", unique = true, nullable = false)
    public int getIdMetodoPagoFactura() {
        return this.idMetodoPagoFactura;
    }

    public void setIdMetodoPagoFactura(int idMetodoPagoFactura) {
        this.idMetodoPagoFactura = idMetodoPagoFactura;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "id_factura", nullable = false)
    public Factura getFactura() {
        return this.factura;
    }

    public void setFactura(Factura factura) {
        this.factura = factura;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "id_plan_pago", nullable = false)
    public PlanPago getPlanPago() {
        return this.planPago;
    }

    public void setPlanPago(PlanPago planPago) {
        this.planPago = planPago;
    }

    @Column(name = "monto_pago", nullable = false)
    public int getMontoPago() {
        return this.montoPago;
    }

    public void setMontoPago(int montoPago) {
        this.montoPago = montoPago;
    }

    @Column(name = "estado", nullable = false)
    public boolean isEstado() {
        return this.estado;
    }

    public void setEstado(boolean estado) {
        this.estado = estado;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fecha_creacion", nullable = false, length = 35)
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }

    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fecha modificacion", length = 35)
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }

    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }

    @Column(name = "usuario_creacion", nullable = false)
    public int getUsuarioCreacion() {
        return this.usuarioCreacion;
    }

    public void setUsuarioCreacion(int usuarioCreacion) {
        this.usuarioCreacion = usuarioCreacion;
    }

    @Column(name = "usuario_modificacion")
    public Integer getUsuarioModificacion() {
        return this.usuarioModificacion;
    }

    public void setUsuarioModificacion(Integer usuarioModificacion) {
        this.usuarioModificacion = usuarioModificacion;
    }

}
