package com.ar.dev.tierra.api.model;
// Generated 17/02/2016 00:47:04 by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PlanPago generated by hbm2java
 */
@Entity
@Table(name = "plan_pago")
public class PlanPago implements Serializable {

    private int idPlanesPago;
    private Tarjeta tarjeta;
    private String nombrePlanesPago;
    private int cuotasPlanesPago;
    private Date fechaInicioPlanes;
    private Date fechaFinalizacionPlanes;
    private int porcentajeInterez;
    private String fechaCierre;
    private boolean estadoPlanes;
    private Date fechaCreacion;
    private Date fechaModificacion;
    private int usuarioCreacion;
    private Integer usuarioMoficacion;

    public PlanPago() {
    }

    public PlanPago(int idPlanesPago, Tarjeta tarjeta, String nombrePlanesPago, int cuotasPlanesPago, Date fechaInicioPlanes, int porcentajeInterez, boolean estadoPlanes, Date fechaCreacion, int usuarioCreacion) {
        this.idPlanesPago = idPlanesPago;
        this.tarjeta = tarjeta;
        this.nombrePlanesPago = nombrePlanesPago;
        this.cuotasPlanesPago = cuotasPlanesPago;
        this.fechaInicioPlanes = fechaInicioPlanes;
        this.porcentajeInterez = porcentajeInterez;
        this.estadoPlanes = estadoPlanes;
        this.fechaCreacion = fechaCreacion;
        this.usuarioCreacion = usuarioCreacion;
    }

    public PlanPago(int idPlanesPago, Tarjeta tarjeta, String nombrePlanesPago, int cuotasPlanesPago, Date fechaInicioPlanes, Date fechaFinalizacionPlanes, int porcentajeInterez, String fechaCierre, boolean estadoPlanes, Date fechaCreacion, Date fechaModificacion, int usuarioCreacion, Integer usuarioMoficacion) {
        this.idPlanesPago = idPlanesPago;
        this.tarjeta = tarjeta;
        this.nombrePlanesPago = nombrePlanesPago;
        this.cuotasPlanesPago = cuotasPlanesPago;
        this.fechaInicioPlanes = fechaInicioPlanes;
        this.fechaFinalizacionPlanes = fechaFinalizacionPlanes;
        this.porcentajeInterez = porcentajeInterez;
        this.fechaCierre = fechaCierre;
        this.estadoPlanes = estadoPlanes;
        this.fechaCreacion = fechaCreacion;
        this.fechaModificacion = fechaModificacion;
        this.usuarioCreacion = usuarioCreacion;
        this.usuarioMoficacion = usuarioMoficacion;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE)
    @Column(name = "id_planes_pago", unique = true, nullable = false)
    public int getIdPlanesPago() {
        return this.idPlanesPago;
    }

    public void setIdPlanesPago(int idPlanesPago) {
        this.idPlanesPago = idPlanesPago;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "tarjeta_plan", nullable = false)
    public Tarjeta getTarjeta() {
        return this.tarjeta;
    }

    public void setTarjeta(Tarjeta tarjeta) {
        this.tarjeta = tarjeta;
    }

    @Column(name = "nombre_planes_pago", nullable = false, length = 150)
    public String getNombrePlanesPago() {
        return this.nombrePlanesPago;
    }

    public void setNombrePlanesPago(String nombrePlanesPago) {
        this.nombrePlanesPago = nombrePlanesPago;
    }

    @Column(name = "cuotas_planes_pago", nullable = false)
    public int getCuotasPlanesPago() {
        return this.cuotasPlanesPago;
    }

    public void setCuotasPlanesPago(int cuotasPlanesPago) {
        this.cuotasPlanesPago = cuotasPlanesPago;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha_inicio_planes", nullable = false, length = 13)
    public Date getFechaInicioPlanes() {
        return this.fechaInicioPlanes;
    }

    public void setFechaInicioPlanes(Date fechaInicioPlanes) {
        this.fechaInicioPlanes = fechaInicioPlanes;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha_finalizacion_planes", length = 13)
    public Date getFechaFinalizacionPlanes() {
        return this.fechaFinalizacionPlanes;
    }

    public void setFechaFinalizacionPlanes(Date fechaFinalizacionPlanes) {
        this.fechaFinalizacionPlanes = fechaFinalizacionPlanes;
    }

    @Column(name = "porcentaje_interez", nullable = false)
    public int getPorcentajeInterez() {
        return this.porcentajeInterez;
    }

    public void setPorcentajeInterez(int porcentajeInterez) {
        this.porcentajeInterez = porcentajeInterez;
    }

    @Column(name = "fecha_cierre", length = 50)
    public String getFechaCierre() {
        return this.fechaCierre;
    }

    public void setFechaCierre(String fechaCierre) {
        this.fechaCierre = fechaCierre;
    }

    @Column(name = "estado_planes", nullable = false)
    public boolean isEstadoPlanes() {
        return this.estadoPlanes;
    }

    public void setEstadoPlanes(boolean estadoPlanes) {
        this.estadoPlanes = estadoPlanes;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha_creacion", nullable = false, length = 13)
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }

    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha_modificacion", length = 13)
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }

    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }

    @Column(name = "usuario_creacion", nullable = false)
    public int getUsuarioCreacion() {
        return this.usuarioCreacion;
    }

    public void setUsuarioCreacion(int usuarioCreacion) {
        this.usuarioCreacion = usuarioCreacion;
    }

    @Column(name = "usuario_moficacion")
    public Integer getUsuarioMoficacion() {
        return this.usuarioMoficacion;
    }

    public void setUsuarioMoficacion(Integer usuarioMoficacion) {
        this.usuarioMoficacion = usuarioMoficacion;
    }

}
