package com.ar.dev.tierra.api.model;
// Generated 11/02/2016 01:28:34 by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.math.BigInteger;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Producto generated by hbm2java
 */
@Entity
@Table(name = "producto")
public class Producto implements Serializable {

    @Id
    @Column(name = "id_producto", unique = true, nullable = false)
    private BigInteger idProducto;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "categoria_producto", nullable = false)
    private Categoria categoria;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "marcas_producto", nullable = false)
    private Marcas marcas;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "proveedor_producto", nullable = false)
    private Proveedor proveedor;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "sexo_producto", nullable = false)
    private Sexo sexo;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "temporada_producto", nullable = false)
    private Temporada temporada;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "tipo_producto", nullable = false)
    private TipoProducto tipoProducto;

    @Column(name = "descripcion", nullable = false, length = 200)
    private String descripcion;

    @Column(name = "color_producto", nullable = false, length = 150)
    private String colorProducto;

    @Column(name = "precio_costo", nullable = false)
    private int precioCosto;

    @Column(name = "precio_venta", nullable = false)
    private int precioVenta;

    @Column(name = "cantidad_producto", nullable = false)
    private int cantidadProducto;

    @Column(name = "cantidad_minima", nullable = false)
    private int cantidadMinima;

    @Column(name = "talla", nullable = false, length = 150)
    private String talla;

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha_producto", length = 13)
    private Date fechaProducto;

    @Column(name = "estado_producto", nullable = false)
    private boolean estadoProducto;

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha_creacion", nullable = false, length = 13)
    private Date fechaCreacion;

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha_modificacion", length = 13)
    private Date fechaModificacion;

    @Column(name = "usuario_creacion", nullable = false)
    private int usuarioCreacion;

    @Column(name = "usuario_modificacion")
    private Integer usuarioModificacion;

    public Producto() {
    }

    public Producto(BigInteger idProducto, Categoria categoria, Marcas marcas, Proveedor proveedor, Sexo sexo, Temporada temporada, TipoProducto tipoProducto, String descripcion, String colorProducto, int precioCosto, int precioVenta, int cantidadProducto, int cantidadMinima, String talla, Date fechaProducto, boolean estadoProducto, Date fechaCreacion, Date fechaModificacion, int usuarioCreacion, Integer usuarioModificacion) {
        this.idProducto = idProducto;
        this.categoria = categoria;
        this.marcas = marcas;
        this.proveedor = proveedor;
        this.sexo = sexo;
        this.temporada = temporada;
        this.tipoProducto = tipoProducto;
        this.descripcion = descripcion;
        this.colorProducto = colorProducto;
        this.precioCosto = precioCosto;
        this.precioVenta = precioVenta;
        this.cantidadProducto = cantidadProducto;
        this.cantidadMinima = cantidadMinima;
        this.talla = talla;
        this.fechaProducto = fechaProducto;
        this.estadoProducto = estadoProducto;
        this.fechaCreacion = fechaCreacion;
        this.fechaModificacion = fechaModificacion;
        this.usuarioCreacion = usuarioCreacion;
        this.usuarioModificacion = usuarioModificacion;
    }

    /**
     * @return the idProducto
     */
    public BigInteger getIdProducto() {
        return idProducto;
    }

    /**
     * @param idProducto the idProducto to set
     */
    public void setIdProducto(BigInteger idProducto) {
        this.idProducto = idProducto;
    }

    /**
     * @return the categoria
     */
    public Categoria getCategoria() {
        return categoria;
    }

    /**
     * @param categoria the categoria to set
     */
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }

    /**
     * @return the marcas
     */
    public Marcas getMarcas() {
        return marcas;
    }

    /**
     * @param marcas the marcas to set
     */
    public void setMarcas(Marcas marcas) {
        this.marcas = marcas;
    }

    /**
     * @return the proveedor
     */
    public Proveedor getProveedor() {
        return proveedor;
    }

    /**
     * @param proveedor the proveedor to set
     */
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }

    /**
     * @return the sexo
     */
    public Sexo getSexo() {
        return sexo;
    }

    /**
     * @param sexo the sexo to set
     */
    public void setSexo(Sexo sexo) {
        this.sexo = sexo;
    }

    /**
     * @return the temporada
     */
    public Temporada getTemporada() {
        return temporada;
    }

    /**
     * @param temporada the temporada to set
     */
    public void setTemporada(Temporada temporada) {
        this.temporada = temporada;
    }

    /**
     * @return the tipoProducto
     */
    public TipoProducto getTipoProducto() {
        return tipoProducto;
    }

    /**
     * @param tipoProducto the tipoProducto to set
     */
    public void setTipoProducto(TipoProducto tipoProducto) {
        this.tipoProducto = tipoProducto;
    }

    /**
     * @return the descripcion
     */
    public String getDescripcion() {
        return descripcion;
    }

    /**
     * @param descripcion the descripcion to set
     */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    /**
     * @return the colorProducto
     */
    public String getColorProducto() {
        return colorProducto;
    }

    /**
     * @param colorProducto the colorProducto to set
     */
    public void setColorProducto(String colorProducto) {
        this.colorProducto = colorProducto;
    }

    /**
     * @return the precioCosto
     */
    public int getPrecioCosto() {
        return precioCosto;
    }

    /**
     * @param precioCosto the precioCosto to set
     */
    public void setPrecioCosto(int precioCosto) {
        this.precioCosto = precioCosto;
    }

    /**
     * @return the precioVenta
     */
    public int getPrecioVenta() {
        return precioVenta;
    }

    /**
     * @param precioVenta the precioVenta to set
     */
    public void setPrecioVenta(int precioVenta) {
        this.precioVenta = precioVenta;
    }

    /**
     * @return the cantidadProducto
     */
    public int getCantidadProducto() {
        return cantidadProducto;
    }

    /**
     * @param cantidadProducto the cantidadProducto to set
     */
    public void setCantidadProducto(int cantidadProducto) {
        this.cantidadProducto = cantidadProducto;
    }

    /**
     * @return the cantidadMinima
     */
    public int getCantidadMinima() {
        return cantidadMinima;
    }

    /**
     * @param cantidadMinima the cantidadMinima to set
     */
    public void setCantidadMinima(int cantidadMinima) {
        this.cantidadMinima = cantidadMinima;
    }

    /**
     * @return the talla
     */
    public String getTalla() {
        return talla;
    }

    /**
     * @param talla the talla to set
     */
    public void setTalla(String talla) {
        this.talla = talla;
    }

    /**
     * @return the fechaProducto
     */
    public Date getFechaProducto() {
        return fechaProducto;
    }

    /**
     * @param fechaProducto the fechaProducto to set
     */
    public void setFechaProducto(Date fechaProducto) {
        this.fechaProducto = fechaProducto;
    }

    /**
     * @return the estadoProducto
     */
    public boolean isEstadoProducto() {
        return estadoProducto;
    }

    /**
     * @param estadoProducto the estadoProducto to set
     */
    public void setEstadoProducto(boolean estadoProducto) {
        this.estadoProducto = estadoProducto;
    }

    /**
     * @return the fechaCreacion
     */
    public Date getFechaCreacion() {
        return fechaCreacion;
    }

    /**
     * @param fechaCreacion the fechaCreacion to set
     */
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    /**
     * @return the fechaModificacion
     */
    public Date getFechaModificacion() {
        return fechaModificacion;
    }

    /**
     * @param fechaModificacion the fechaModificacion to set
     */
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }

    /**
     * @return the usuarioCreacion
     */
    public int getUsuarioCreacion() {
        return usuarioCreacion;
    }

    /**
     * @param usuarioCreacion the usuarioCreacion to set
     */
    public void setUsuarioCreacion(int usuarioCreacion) {
        this.usuarioCreacion = usuarioCreacion;
    }

    /**
     * @return the usuarioModificacion
     */
    public Integer getUsuarioModificacion() {
        return usuarioModificacion;
    }

    /**
     * @param usuarioModificacion the usuarioModificacion to set
     */
    public void setUsuarioModificacion(Integer usuarioModificacion) {
        this.usuarioModificacion = usuarioModificacion;
    }

}
