package com.ar.dev.tierra.api.model;
// Generated 17/02/2016 00:47:04 by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tarjeta generated by hbm2java
 */
@Entity
@Table(name = "tarjeta")
public class Tarjeta implements Serializable {

    private int idTarjeta;
    private EntidadBancaria entidadBancaria;
    private MedioPago medioPago;
    private String nombreTarjeta;
    private int tarjetaMedio;
    private int tarjetaEntidad;
    private boolean estadoTarjeta;
    private Date fechaCreacion;
    private Date fechaModificacion;
    private Integer usuarioCreacion;
    private Integer usuarioModificacion;

    public Tarjeta() {
    }

    public Tarjeta(EntidadBancaria entidadBancaria, MedioPago medioPago, String nombreTarjeta, int tarjetaMedio, int tarjetaEntidad, boolean estadoTarjeta, Date fechaCreacion) {
        this.entidadBancaria = entidadBancaria;
        this.medioPago = medioPago;
        this.nombreTarjeta = nombreTarjeta;
        this.tarjetaMedio = tarjetaMedio;
        this.tarjetaEntidad = tarjetaEntidad;
        this.estadoTarjeta = estadoTarjeta;
        this.fechaCreacion = fechaCreacion;
    }

    public Tarjeta(int idTarjeta, EntidadBancaria entidadBancaria, MedioPago medioPago, String nombreTarjeta, int tarjetaMedio, int tarjetaEntidad, boolean estadoTarjeta, Date fechaCreacion, Date fechaModificacion, Integer usuarioCreacion, Integer usuarioModificacion) {
        this.idTarjeta = idTarjeta;
        this.entidadBancaria = entidadBancaria;
        this.medioPago = medioPago;
        this.nombreTarjeta = nombreTarjeta;
        this.tarjetaMedio = tarjetaMedio;
        this.tarjetaEntidad = tarjetaEntidad;
        this.estadoTarjeta = estadoTarjeta;
        this.fechaCreacion = fechaCreacion;
        this.fechaModificacion = fechaModificacion;
        this.usuarioCreacion = usuarioCreacion;
        this.usuarioModificacion = usuarioModificacion;
    }

    @Id

    @Column(name = "id_tarjeta", unique = true, nullable = false)
    public int getIdTarjeta() {
        return this.idTarjeta;
    }

    public void setIdTarjeta(int idTarjeta) {
        this.idTarjeta = idTarjeta;
    }

    @OneToOne(fetch = FetchType.EAGER)
    @PrimaryKeyJoinColumn
    public EntidadBancaria getEntidadBancaria() {
        return this.entidadBancaria;
    }

    public void setEntidadBancaria(EntidadBancaria entidadBancaria) {
        this.entidadBancaria = entidadBancaria;
    }

    @OneToOne(fetch = FetchType.EAGER)
    @PrimaryKeyJoinColumn
    public MedioPago getMedioPago() {
        return this.medioPago;
    }

    public void setMedioPago(MedioPago medioPago) {
        this.medioPago = medioPago;
    }

    @Column(name = "nombre_tarjeta", nullable = false, length = 150)
    public String getNombreTarjeta() {
        return this.nombreTarjeta;
    }

    public void setNombreTarjeta(String nombreTarjeta) {
        this.nombreTarjeta = nombreTarjeta;
    }

    @Column(name = "tarjeta_medio", nullable = false)
    public int getTarjetaMedio() {
        return this.tarjetaMedio;
    }

    public void setTarjetaMedio(int tarjetaMedio) {
        this.tarjetaMedio = tarjetaMedio;
    }

    @Column(name = "tarjeta_entidad", nullable = false)
    public int getTarjetaEntidad() {
        return this.tarjetaEntidad;
    }

    public void setTarjetaEntidad(int tarjetaEntidad) {
        this.tarjetaEntidad = tarjetaEntidad;
    }

    @Column(name = "estado_tarjeta", nullable = false)
    public boolean isEstadoTarjeta() {
        return this.estadoTarjeta;
    }

    public void setEstadoTarjeta(boolean estadoTarjeta) {
        this.estadoTarjeta = estadoTarjeta;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha_creacion", nullable = false, length = 13)
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }

    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha_modificacion", length = 13)
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }

    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }

    @Column(name = "usuario_creacion")
    public Integer getUsuarioCreacion() {
        return this.usuarioCreacion;
    }

    public void setUsuarioCreacion(Integer usuarioCreacion) {
        this.usuarioCreacion = usuarioCreacion;
    }

    @Column(name = "usuario_modificacion")
    public Integer getUsuarioModificacion() {
        return this.usuarioModificacion;
    }

    public void setUsuarioModificacion(Integer usuarioModificacion) {
        this.usuarioModificacion = usuarioModificacion;
    }

}
