package com.ar.dev.tierra.api.model;
// Generated 31/01/2016 21:41:14 by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Usuarios generated by hbm2java
 */
@Entity
@Table(name = "usuarios")
public class Usuarios implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE)
    @Column(name = "id_usuario", unique = true, nullable = false)
    private int idUsuario;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "roles_usuario", nullable = false)
    private Roles roles;

    @Column(name = "nombre", nullable = false, length = 100)
    private String nombre;

    @Column(name = "apellido", nullable = false, length = 100)
    private String apellido;

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha_nacimiento", nullable = false, length = 13)
    private Date fechaNacimiento;

    @Column(name = "dni", unique = true, nullable = false)
    private int dni;

    @Column(name = "email", length = 100)
    private String email;

    @Column(name = "telefono")
    private String telefono;

    @Column(name = "domicilio", nullable = false, length = 100)
    private String domicilio;

    @Column(name = "provincia", nullable = false, length = 100)
    private String provincia;

    @Column(name = "username", unique = true, nullable = false, length = 40)
    private String username;

    @Column(name = "password", nullable = false, length = 300)
    private String password;

    @Column(name = "imagen")
    private byte[] imagen;

    @Column(name = "estado", nullable = false)
    private boolean estado;

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha_creacion", nullable = false, length = 13)
    private Date fechaCreacion;

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha_modificacion", length = 13)
    private Date fechaModificacion;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "ultima_conexion", nullable = false, length = 35)
    private Date ultimaConexion;

    @Column(name = "id_usuario_creacion", nullable = false)
    private int idUsuarioCreacion;

    @Column(name = "id_usuario_modificacion")
    private int idUsuarioModificacion;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "usuario_sucursal", nullable = false)
    private Sucursal usuarioSucursal;

    public Usuarios() {
    }

    public Usuarios(int idUsuario, Roles roles, String nombre, String apellido, Date fechaNacimiento, int dni, String email, String telefono, String domicilio, String provincia, String username, String password, byte[] imagen, boolean estado, Date fechaCreacion, Date fechaModificacion, Date ultimaConexion, int idUsuarioCreacion, int idUsuarioModificacion, Sucursal usuarioSucursal) {
        this.idUsuario = idUsuario;
        this.roles = roles;
        this.nombre = nombre;
        this.apellido = apellido;
        this.fechaNacimiento = fechaNacimiento;
        this.dni = dni;
        this.email = email;
        this.telefono = telefono;
        this.domicilio = domicilio;
        this.provincia = provincia;
        this.username = username;
        this.password = password;
        this.imagen = imagen;
        this.estado = estado;
        this.fechaCreacion = fechaCreacion;
        this.fechaModificacion = fechaModificacion;
        this.ultimaConexion = ultimaConexion;
        this.idUsuarioCreacion = idUsuarioCreacion;
        this.idUsuarioModificacion = idUsuarioModificacion;
        this.usuarioSucursal = usuarioSucursal;
    }

    /**
     * @return the idUsuario
     */
    public int getIdUsuario() {
        return idUsuario;
    }

    /**
     * @param idUsuario the idUsuario to set
     */
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }

    /**
     * @return the roles
     */
    public Roles getRoles() {
        return roles;
    }

    /**
     * @param roles the roles to set
     */
    public void setRoles(Roles roles) {
        this.roles = roles;
    }

    /**
     * @return the nombre
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * @param nombre the nombre to set
     */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /**
     * @return the apellido
     */
    public String getApellido() {
        return apellido;
    }

    /**
     * @param apellido the apellido to set
     */
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    /**
     * @return the fechaNacimiento
     */
    public Date getFechaNacimiento() {
        return fechaNacimiento;
    }

    /**
     * @param fechaNacimiento the fechaNacimiento to set
     */
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }

    /**
     * @return the dni
     */
    public int getDni() {
        return dni;
    }

    /**
     * @param dni the dni to set
     */
    public void setDni(int dni) {
        this.dni = dni;
    }

    /**
     * @return the email
     */
    public String getEmail() {
        return email;
    }

    /**
     * @param email the email to set
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * @return the telefono
     */
    public String getTelefono() {
        return telefono;
    }

    /**
     * @param telefono the telefono to set
     */
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    /**
     * @return the domicilio
     */
    public String getDomicilio() {
        return domicilio;
    }

    /**
     * @param domicilio the domicilio to set
     */
    public void setDomicilio(String domicilio) {
        this.domicilio = domicilio;
    }

    /**
     * @return the provincia
     */
    public String getProvincia() {
        return provincia;
    }

    /**
     * @param provincia the provincia to set
     */
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }

    /**
     * @return the username
     */
    public String getUsername() {
        return username;
    }

    /**
     * @param username the username to set
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * @return the password
     */
    public String getPassword() {
        return password;
    }

    /**
     * @param password the password to set
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * @return the imagen
     */
    public byte[] getImagen() {
        return imagen;
    }

    /**
     * @param imagen the imagen to set
     */
    public void setImagen(byte[] imagen) {
        this.imagen = imagen;
    }

    /**
     * @return the estado
     */
    public boolean isEstado() {
        return estado;
    }

    /**
     * @param estado the estado to set
     */
    public void setEstado(boolean estado) {
        this.estado = estado;
    }

    /**
     * @return the fechaCreacion
     */
    public Date getFechaCreacion() {
        return fechaCreacion;
    }

    /**
     * @param fechaCreacion the fechaCreacion to set
     */
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    /**
     * @return the fechaModificacion
     */
    public Date getFechaModificacion() {
        return fechaModificacion;
    }

    /**
     * @param fechaModificacion the fechaModificacion to set
     */
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }

    /**
     * @return the ultimaConexion
     */
    public Date getUltimaConexion() {
        return ultimaConexion;
    }

    /**
     * @param ultimaConexion the ultimaConexion to set
     */
    public void setUltimaConexion(Date ultimaConexion) {
        this.ultimaConexion = ultimaConexion;
    }

    /**
     * @return the idUsuarioCreacion
     */
    public int getIdUsuarioCreacion() {
        return idUsuarioCreacion;
    }

    /**
     * @param idUsuarioCreacion the idUsuarioCreacion to set
     */
    public void setIdUsuarioCreacion(int idUsuarioCreacion) {
        this.idUsuarioCreacion = idUsuarioCreacion;
    }

    /**
     * @return the idUsuarioModificacion
     */
    public int getIdUsuarioModificacion() {
        return idUsuarioModificacion;
    }

    /**
     * @param idUsuarioModificacion the idUsuarioModificacion to set
     */
    public void setIdUsuarioModificacion(int idUsuarioModificacion) {
        this.idUsuarioModificacion = idUsuarioModificacion;
    }

    /**
     * @return the usuarioSucursal
     */
    public Sucursal getUsuarioSucursal() {
        return usuarioSucursal;
    }

    /**
     * @param usuarioSucursal the usuarioSucursal to set
     */
    public void setUsuarioSucursal(Sucursal usuarioSucursal) {
        this.usuarioSucursal = usuarioSucursal;
    }

}
